Repository hmcts/opal-user-service, pull requests merged in 2025-08, with the labels that each got.

#214 PO-1644-Add SQL migration for new account maintenance and notes permi…
  src/main/resources/db/migration/V20250811_030__account_maintenance_note_perm.sql
Labels: ns:opal, prd:opal, rel:opal-user-service-pr-214

#239 Updated ingres host
  charts/opal-user-service/Chart.yaml
  charts/opal-user-service/values.yaml
Labels: ns:opal, prd:opal, enable_keep_helm, rel:opal-user-service-pr-239

#232 PO-2097 - Add Permission for Account Maintenance and Notes
  bin/main/db/migration/V20250820_030__account_maintenance_note_perm.sql
  src/main/resources/application.yaml
Labels: ns:opal, prd:opal, rel:opal-user-service-pr-232
